name: Notify Ktranslate

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: kentik/ktranslate
          event-type: new-snmp-profiles
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'